config/routes.rb
Rails.application.routes.draw do
  resources :gigs
  resources :instruments
  devise_for :members, controllers: { registrations: 'registrations' }
  # get 'members/index'
  get 'home/index'
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'gig_signup/:id', to: 'gigs#signup', as: 'gig_signup'
  get 'gig_dropout/:id', to: 'gigs#dropout', as: 'gig_dropout'

  root 'home#index'
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :gig_admin, class_name: 'Member'
  has_and_belongs_to_many :members
  validate :check_gig_admin_has_permission

  has_rich_text :about_r

  scope :past, -> { where(when: Time.now - 1.year..Time.now ) }
  scope :future, -> { where(when: Time.now..Time.now + 2.years) }

  def players
    members
  end

  private

  def check_gig_admin_has_permission
    errors.add(:gig_admin, 'is not allowed') unless gig_admin.gig_admin?
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  load_and_authorize_resource
  before_action :set_gig, only: [:show, :edit, :update, :destroy, :signup, :dropout]

  # GET /gigs
  # GET /gigs.json
  def index
    @past_gigs = Gig.past
    @future_gigs = Gig.future
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    # byebug
  end

  # GET /gigs/new
  def new
    @gig_admins = Member.where(gig_admin: true)
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
    @gig_admins = Member.where(gig_admin: true)
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)
    @gig.gig_admin = Member.find(gig_params[:gig_admin_id])
    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def signup
    @gig.players << @current_member unless @gig.players.include? @current_member
    respond_to do |format|
      format.html { redirect_to @gig, notice: 'Thanks for signing up!' }
      format.json { render :show, status: :ok, location: @gig }
    end
  end

  def dropout
    @gig.players.delete(@current_member) if @gig.players.include? @current_member
    respond_to do |format|
      format.html { redirect_to @gig, alert: "Awww sorry you can't make it!" }
      format.json { render :show, status: :ok, location: @gig }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gig
    @gig = Gig.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gig_params
    params.require(:gig).permit(:title, :where, :when, :band_contact, :event_contact,
                                :gig_admin_id, :confirmed, :about, :about_r, :signup, :dropout,
                                :high_payer, :charity)
  end
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/_form.html.erb
<%= form_with(model: gig, local: true) do |form| %>
  <% if gig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gig.errors.count, "error") %> prohibited this gig from being saved:</h2>

      <ul>
      <% gig.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="tile is-ancestor">
  <div class="tile is-6 is-vertical is-parent">
    <div class="tile is-child box">

      <p class="title">Details</p>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :title, class: 'label' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <%= form.text_field :title, class: 'input' %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :where, class: 'label' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <%= form.text_field :where, class: 'input' %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :when, class: 'label' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <%= form.datetime_select :when, class: 'input' %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :gig_admin, class: 'label' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <% options = options_from_collection_for_select(@gig_admins, 'id', 'first_name') %>
              <%= form.select :gig_admin_id,  options, {}, { class: 'select is-warning' } %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :event_contact, class: 'label' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <%= form.text_field :event_contact, class: 'input' %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :high_payer, class: 'checkbox' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <%= form.check_box :high_payer, class: 'checkbox' %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :charity, class: 'checkbox' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <%= form.check_box :charity, class: 'checkbox' %>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label">
        <%= form.label :confirmed, class: 'checkbox' %>
        </div>
        <div class="field-body">
          <div calss="field">
            <div class="control">
              <%= form.check_box :confirmed, class: 'checkbox' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tile is-parent">
    <div class="tile is-child box">
      <p class="title">About</p>
       <div class="field">

        <%= form.rich_text_area :about_r %>
      </div>
    </div>
  </div>
</div>
  <div class="actions">
    <%= form.submit   class: 'button' %>
  </div>

<% end %>

app/views/gigs/edit.html.erb
<h1 class="title">Editing Gig</h1>

<%= render 'form', gig: @gig %>

<%= link_to 'Show', @gig %> |
<%= link_to 'Back', gigs_path %>

app/views/gigs/index.html.erb
<h1 class="title">Gigs</h1>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Where</th>
      <th scope="col">When</th>
      <th scope="col">Band contact</th>
      <th scope="col">Event contact</th>
      <th scope="col">Confirmed</th>
      <th>Signed Up? </th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @future_gigs.each do |gig| %>
      <tr >
        <th scope="row"><%= link_to gig.title, gig %></th>
        <td><%= gig.where %></td>
        <td><%= gig.when.to_formatted_s(:short) %></td>
        <td><%= gig.gig_admin.first_name %></td>
        <td><%= gig.event_contact %></td>
        <% if gig.confirmed %>
        <td class="is-success">Yes!</td>
        <% else %>
        <td class="is-danger">No</td>
        <% end %>
        <% if gig.players.include? current_member %>
        <td class="is-success">Yes!</td>
        <% else %>
        <td class="is-danger">No</td>
        <% end %>
        <td><% if can? :edit, :gigs %><%= link_to 'Edit', edit_gig_path(gig) %> <% end %></td>
        <td><% if can? :destroy, :gigs %><%= link_to 'Destroy', gig, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1 class="title">Past Gigs</h1>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Where</th>
      <th scope="col">When</th>
      <th scope="col">Band contact</th>
      <th scope="col">Event contact</th>
      <th scope="col">Confirmed</th>
      <th>Signed Up? </th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @past_gigs.each do |gig| %>
      <tr >
        <th scope="row"><%= link_to gig.title, gig %></th>
        <td><%= gig.where %></td>
        <td><%= gig.when.to_formatted_s(:short) %></td>
        <td><%= gig.when.strftime('%A') %></td>
        <td><%= gig.gig_admin.first_name %></td>
        <td><%= gig.event_contact %></td>
        <% if gig.confirmed %>
        <td class="is-success">Yes!</td>
        <% else %>
        <td class="is-danger">No</td>
        <% end %>
        <% if gig.players.include? current_member %>
        <td class="is-success">Yes!</td>
        <% else %>
        <td class="is-danger">No</td>
        <% end %>
        <td><% if can? :edit, :gigs %><%= link_to 'Edit', edit_gig_path(gig) %> <% end %></td>
        <td><% if can? :destroy, :gigs %><%= link_to 'Destroy', gig, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, @gigs %>
  <%= link_to 'New Gig', new_gig_path %>
<% end %>

app/views/gigs/new.html.erb
<h1 class="title"> New Gig</h1>

<%= render 'form', gig: @gig %>

<%= link_to 'Back', gigs_path %>

app/views/gigs/show.html.erb
<h1 class="title"><%= @gig.title %>
<% if @gig.confirmed %>
<span class="tag is-success is-large">Confirmed</span>
<% else %>
<span class="tag is-info is-large">Unconfirmed</span>

<% end %>
<% if @gig.high_payer %><span class="tag is-small">£ $ €</span><% end %>
<% if @gig.charity %><span class="tag is-small">Charity</span><% end %>

</h1>
<div class="tile is-ancestor">
  <div class="tile is-6 is-vertical is-parent">
    <div class="tile is-child box">
      <p class="title">Details</p>
    <p>
      <strong>Where:</strong>
      <%= @gig.where %>
    </p>

    <p>
      <strong>When:</strong>
      <%= @gig.when.to_formatted_s(:short) %>
    </p>

    <p>
      <strong>Band contact:</strong>
      <%= @gig.gig_admin.first_name %>
    </p>

    <p>
      <strong>Event contact:</strong>
      <%= @gig.event_contact %>
    </p>    </div>


    <div class="tile is-child box">
      <p class="title">Players Signed Up</p>
      <p>
      <strong>Drums: <span class="tag"><%= @gig.players.drummers.count %> </span></strong>
      <%= @gig.players.drummers.map { |m| m.first_name}.to_sentence %>
      </p>
      <p>
      <strong>Bass: <span class="tag"><%= @gig.players.basses.count %> </span></strong>
      <%= @gig.players.basses.map { |m| m.first_name}.to_sentence %>
      </p>
      <p>
      <strong>Trombones: <span class="tag"><%= @gig.players.boners.count %> </span></strong>
      <%= @gig.players.boners.map { |m| m.first_name}.to_sentence %>
      </p>
      <strong>Trumpeters: <span class="tag"><%= @gig.players.trumpeters.count %> </span></strong>
      <%= @gig.players.trumpeters.map { |m| m.first_name}.to_sentence %>
      </p>
      <p>
      <strong>Tenor Saxes: <span class="tag"><%= @gig.players.tenor_saxes.count %> </span></strong>
      <%= @gig.players.tenor_saxes.map { |m| m.first_name}.to_sentence %>
      </p>
      <p>
      <strong>Alto Saxes: <span class="tag"><%= @gig.players.alto_saxes.count %> </span></strong>
      <%= @gig.players.alto_saxes.map { |m| m.first_name}.to_sentence %>
      </p>
      <p>
      <strong>Soprano Saxes: <span class="tag"><%= @gig.players.soprano_saxes.count %> </span></strong>
      <%= @gig.players.soprano_saxes.map { |m| m.first_name}.to_sentence %>
      </p>
    </div>
  </div>


  <div class="tile is-parent">
    <div class="tile is-child box">
      <p class="title">About</p>
      <p><%= @gig.about_r %></p>
    </div>
  </div>
</div>

<% if @gig.players.include? current_member %>
<%= link_to 'Drop Out', gig_dropout_path, id: "gig_dropout"  %> |
<% else %>
<%= link_to 'Sign Up', gig_signup_path, id: "gig_signup"  %> |
<% end %>

<% if can? :edit, :gigs %><%= link_to 'Edit', edit_gig_path(@gig) %> |<% end %>
<%= link_to 'Back', gigs_path %>