config/routes.rb
Rails.application.routes.draw do
  resources :gigs
  resources :instruments
  devise_for :members, controllers: { registrations: 'registrations' }
  # get 'members/index'
  get 'home/index'
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'gig_signup/:id', to: 'gigs#signup', as: 'gig_signup'
  get 'gig_dropout/:id', to: 'gigs#dropout', as: 'gig_dropout'

  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Band,Aye?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
  <nav class="navbar is-info" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <%= Settings.application.title %>
      </a>
      <a class="navbar-item" href="/gigs">Gigs</a>
      <a class="navbar-item" href="/members">Members</a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">

      <div class="navbar-end">
        <div class="navbar-item">
            <% if member_signed_in? %>
                <div class="navbar-item">Hi <%= current_member.first_name %>!</div>
                <div class="buttons">
                <%= link_to 'Sign out', destroy_member_session_path, method: :delete, class: 'button ' %>
              </div>
              <% else %>
          <div class="buttons">

                <%= link_to 'Register', new_member_registration_path, class: 'button is-primary' %>
                <%= link_to 'Sign in', new_member_session_path, class: 'button is-light' %>
          </div>
            <% end %>

        </div>
      </div>
    </div>
  </nav>

      <% if flash[:notice] %>
        <p class="notification is-success" role="alert">  <button class="delete"></button><%= notice %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="notification is-warning" role="alert" class="alert">  <button class="delete"></button><%= alert %></p>
      <% end %>

      <div class="container">
        <div class="section">
          <%= yield %>
        </div>
      </div>
  </body>
</html>